console.log("==========Basic Operators==========");
console.log(`Addition 2 + 3 is ${2+3}`);
console.log(`Subtraction  5 - 2 is ${5-2}`);
console.log(`M<ultiplication 5 * 3 is ${5*3}`);
console.log(`Division 5 / 2 is ${5/2}`);
console.log(`Remainder 5 % 2 is ${5%2}`);
console.log(`=========Increment and Decrement========`);
let x = 5;
console.log(`Increment ++5 is ${++x}`);
console.log(`Current Value is ${x}`);
console.log(`Increment 5++ is ${x++}`);
console.log(`Current Value is ${x}`);
console.log(`Decrement --5 is ${--x}`);
console.log(`Current Value is ${x}`);
console.log(`Decrement 5-- is ${x--}`);
console.log(`Current Value is ${x}`);
